version: '3.8'

services:
  frontend:
    container_name: car-users-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
